import "common_base.proto";

message CClientMetrics_ReportClientError_Notification {
	optional string product = 1;
	optional string version = 2;
	repeated .CClientMetrics_ReportClientError_Notification_Error errors = 3;
	repeated string tags = 4;
}

// Used by: common.proto
message CClientMetrics_ReportClientError_Notification_Error {
	optional string identifier = 1;
	optional string message = 2;
	optional uint32 count = 3;
	optional string context = 4;
}

// Used by: common.proto
message CVRGamepadUI_Frame {
	optional uint32 frame_id = 1;
	optional .CVRGamepadUI_Frame_FrameMenu menu = 2;
	repeated .CVRGamepadUIShared_Action action_definitions = 3;
	optional .CVRGamepadUI_Frame_FrameControls controls = 4;
	optional bool is_vrlink_remote = 5;
	optional .CVRGamepadUI_Frame_FrameActions frame_actions = 6;
	repeated string steamui_page_overlay_keys = 7;
	optional string tmp_title = 1000;
}

// Used by: common.proto
message CVRGamepadUI_Frame_FrameActions {
	optional uint32 focus_main_panel_action = 1;
	optional uint32 focus_left_frame_menu_action = 2;
}

// Used by: common.proto
message CVRGamepadUI_Frame_FrameControls {
	repeated .CVRGamepadUI_Frame_FrameControls_Item items_for_bottom_frame_controls = 1;
	repeated .CVRGamepadUI_Frame_FrameControls_Item items_for_tab_hover_menu = 2;
}

// Used by: common.proto
message CVRGamepadUI_Frame_FrameControls_Item {
	optional int32 type = 1 [(.description) = "enum"];
	optional uint32 action_id = 2;
}

// Used by: common.proto
message CVRGamepadUI_Frame_FrameMenu {
	repeated .CVRGamepadUI_Frame_FrameMenu_Item items_for_left_frame_menu = 1;
	repeated .CVRGamepadUI_Frame_FrameMenu_Item items_for_tab_hover_menu = 2;
}

// Used by: common.proto
message CVRGamepadUI_Frame_FrameMenu_Item {
	optional int32 type = 1 [(.description) = "enum"];
	optional uint32 action_id = 2;
	optional .CVRGamepadUI_Frame_FrameMenu_Item_SteamMainMenuOptions steam_main_menu_options = 3;
	optional .CVRGamepadUI_Frame_FrameMenu_Item_SteamGameInfo steam_game_info = 4;
	optional .CVRGamepadUI_Frame_FrameMenu_Item_SteamGameWindowItemsOptions steam_game_window_item_options = 5;
}

// Used by: common.proto
message CVRGamepadUI_Frame_FrameMenu_Item_SteamGameInfo {
	optional uint32 app_id = 1;
}

// Used by: common.proto
message CVRGamepadUI_Frame_FrameMenu_Item_SteamGameWindowItemsOptions {
	optional bool show_for_single_window = 1;
}

// Used by: common.proto
message CVRGamepadUI_Frame_FrameMenu_Item_SteamMainMenuOptions {
	optional bool allow_show_as_active = 1;
}

message CVRGamepadUI_Message_DashboardActionInvoked_Request {
	optional uint32 action_id = 1;
	optional bool toggle_value = 2;
}

message CVRGamepadUI_Message_DashboardActionInvoked_Response {
}

message CVRGamepadUI_Message_DashboardDesktopWindowClicked_Request {
	optional uint32 window_id = 1;
}

message CVRGamepadUI_Message_DashboardDesktopWindowClicked_Response {
}

message CVRGamepadUI_Message_DashboardTabClicked_Request {
	optional uint32 tab_id = 1;
}

message CVRGamepadUI_Message_DashboardTabClicked_Response {
}

message CVRGamepadUI_Message_Error_Response {
	optional int32 error_code = 1 [(.description) = "enum"];
	optional string error_description = 2;
	optional int32 origin = 3 [(.description) = "enum"];
	optional bool was_transmitted = 4;
}

message CVRGamepadUI_Message_ExecuteSteamURL_Request {
	optional string url = 1;
}

message CVRGamepadUI_Message_ExecuteSteamURL_Response {
}

message CVRGamepadUI_Message_GetAppIcon_Request {
	optional uint32 app_id = 1;
}

message CVRGamepadUI_Message_GetAppIcon_Response {
	optional string icon_url = 1;
}

message CVRGamepadUI_Message_Header {
	optional string name = 1;
	optional uint32 message_id = 2;
	optional uint32 response_to_message_id = 3;
	optional bool is_error_response = 4;
}

message CVRGamepadUI_Message_HideDashboardPopup_Request {
	optional uint32 dashboard_popup_id = 1;
}

message CVRGamepadUI_Message_HideDashboardPopup_Response {
}

message CVRGamepadUI_Message_InitFrameSystem_Request {
}

message CVRGamepadUI_Message_InitFrameSystem_Response {
}

message CVRGamepadUI_Message_RemoteVideoStream_Request {
	optional uint32 source_accountid = 1;
	optional string video_uniqueid = 2;
}

message CVRGamepadUI_Message_RemoteVideoStream_Response {
}

message CVRGamepadUI_Message_ReportVRPanelErrorBoundaryError_Request {
	optional string error_name = 1;
	optional string error_message_with_stack = 2;
}

message CVRGamepadUI_Message_ReportVRPanelErrorBoundaryError_Response {
}

message CVRGamepadUI_Message_ResetHMDSettings_Request {
}

message CVRGamepadUI_Message_ResetHMDSettings_Response {
}

message CVRGamepadUI_Message_SetCurrentLanguage_Request {
	optional string language = 1;
}

message CVRGamepadUI_Message_SetCurrentLanguage_Response {
}

message CVRGamepadUI_Message_SetDisplayBrightness_Request {
	optional float user_brightness_value = 1;
}

message CVRGamepadUI_Message_SetDisplayBrightness_Response {
}

message CVRGamepadUI_Message_SetHMDSettings_Request {
	optional float user_brightness_value = 1;
	optional float refresh_rate_value = 2;
	optional bool supersample_manual_override = 3;
	optional float supersample_scale_value = 4;
	optional uint32 frames_to_throttle = 5;
	optional bool motion_smoothing = 6;
	optional string performance_profile_value = 7;
	optional bool perf_graph_in_hmd = 8;
	optional bool record_vr_stats = 9;
}

message CVRGamepadUI_Message_SetHMDSettings_Response {
}

message CVRGamepadUI_Message_ShowDashboardPopup_Request {
	optional uint32 dashboard_popup_id = 1;
	optional string popup_overlay_key = 2;
	optional string parent_overlay_key = 3;
	optional .CVRGamepadUI_Message_ShowDashboardPopup_Request_NormalizedPosition origin_on_parent = 4;
	optional .CVRGamepadUI_Message_ShowDashboardPopup_Request_NormalizedPosition origin_on_popup = 5;
	optional .CVRGamepadUI_Message_ShowDashboardPopup_Request_Position offset = 6;
	optional .CVRGamepadUI_Message_ShowDashboardPopup_Request_Rotation rotation = 7;
	optional bool inherit_parent_pitch = 8;
	optional bool inherit_parent_curvature = 9;
	optional .CVRGamepadUI_Message_ShowDashboardPopup_Request_Rect clip_rect = 10;
	optional bool interactive = 11;
	optional bool only_visible_with_laser = 12;
	optional string parent_device_path = 13;
	optional int32 sort_order = 14 [(.description) = "enum"];
	optional int32 parent_enum = 15 [(.description) = "enum"];
	optional int32 special_identifier = 16 [(.description) = "enum"];
	optional .CVRGamepadUI_Message_ShowDashboardPopup_Request_Scale scale = 17;
}

// Used by: common.proto
message CVRGamepadUI_Message_ShowDashboardPopup_Request_NormalizedPosition {
	optional float x = 1;
	optional float y = 2;
}

// Used by: common.proto
message CVRGamepadUI_Message_ShowDashboardPopup_Request_Position {
	optional float x_pixels = 1;
	optional float y_pixels = 2;
	optional float z_pixels = 3;
	optional float x_meters = 4;
	optional float y_meters = 5;
	optional float z_meters = 6;
}

// Used by: common.proto
message CVRGamepadUI_Message_ShowDashboardPopup_Request_Rect {
	optional float u_min = 1;
	optional float v_min = 2;
	optional float u_max = 3;
	optional float v_max = 4;
}

// Used by: common.proto
message CVRGamepadUI_Message_ShowDashboardPopup_Request_Rotation {
	optional float pitch_degrees = 1;
	optional float yaw_degrees = 2;
}

// Used by: common.proto
message CVRGamepadUI_Message_ShowDashboardPopup_Request_Scale {
	optional float scaler_value = 1;
}

message CVRGamepadUI_Message_ShowDashboardPopup_Response {
}

message CVRGamepadUI_Message_ShowGame_Request {
	optional string overlay_key = 1;
}

message CVRGamepadUI_Message_ShowGame_Response {
}

message CVRGamepadUI_Message_ShowOverlay_Request {
	optional string overlay_key = 1;
}

message CVRGamepadUI_Message_ShowOverlay_Response {
}

message CVRGamepadUI_Message_UpdateFrameUIs_Request {
	repeated .CVRGamepadUI_Frame updated_frames = 1;
	repeated uint32 deleted_frames = 2;
	repeated uint32 shown_frames = 3;
	repeated uint32 hidden_frames = 4;
}

message CVRGamepadUI_Message_UpdateFrameUIs_Response {
	repeated .CVRGamepadUI_Message_UpdateFrameUIs_Response_FrameUpdateResult results = 1;
}

// Used by: common.proto
message CVRGamepadUI_Message_UpdateFrameUIs_Response_FrameUpdateResult {
	optional uint32 frame_id = 1;
	optional uint32 frame_menu_dashboard_popup_id = 2;
}

// Used by: common.proto
message CVRGamepadUIShared_Action {
	optional uint32 action_id = 1;
	optional string display_name = 2;
	optional int32 invocation = 3 [(.description) = "enum"];
	optional .CVRGamepadUIShared_Icon icon = 4;
	optional .CVRGamepadUIShared_Icon icon_active = 5;
	optional bool enabled = 6;
	optional bool active = 7;
}

// Used by: common.proto
message CVRGamepadUIShared_DEPRECATED_DashboardActionIcon {
	optional int32 enum = 1 [(.description) = "enum"];
}

// Used by: common.proto
message CVRGamepadUIShared_DEPRECATED_DashboardBarAction {
	optional uint32 action_id = 1;
	optional bool visible_in_dashboard_bar = 2;
	optional bool enabled = 3;
	optional string display_name = 4;
	optional .CVRGamepadUIShared_DEPRECATED_DashboardActionIcon deprecated_icon = 5;
	optional .CVRGamepadUIShared_DEPRECATED_DashboardActionIcon deprecated_icon_active = 6;
	optional int32 invocation = 7 [(.description) = "enum"];
	optional bool active = 8;
	optional int32 special_invocation = 9 [(.description) = "enum"];
	optional bool visible_in_menu = 10;
	optional bool is_menu = 11;
	optional uint32 parent_menu_action_id = 12;
	optional .CVRGamepadUIShared_Icon icon = 13;
	optional .CVRGamepadUIShared_Icon icon_active = 14;
}

// Used by: common.proto
message CVRGamepadUIShared_DEPRECATED_DashboardTabIcon {
	optional int32 enum = 1 [(.description) = "enum"];
	optional uint32 appid = 2;
	optional string overlay = 3;
	optional uint32 hwnd = 4;
}

// Used by: common.proto
message CVRGamepadUIShared_Icon {
	optional int32 enum = 1 [(.description) = "enum"];
	optional uint32 appid = 2;
	optional string overlay = 3;
	optional uint32 hwnd = 4;
}

message CVRGamepadUIShared_PathProperty_DashboardBarActions {
	repeated .CVRGamepadUIShared_DEPRECATED_DashboardBarAction deprecated_actions = 1;
	repeated .CVRGamepadUIShared_Action defined_actions = 2;
	repeated .CVRGamepadUIShared_PathProperty_DashboardBarActions_BarButton bar_buttons = 3;
	repeated .CVRGamepadUIShared_PathProperty_DashboardBarActions_BarMenuItem bar_menu_items = 4;
	repeated uint32 playspace_actions = 5;
}

// Used by: common.proto
message CVRGamepadUIShared_PathProperty_DashboardBarActions_BarButton {
	optional int32 type = 1 [(.description) = "enum"];
	optional uint32 action_id = 2;
	optional bool is_main_hamburger_menu = 3;
}

// Used by: common.proto
message CVRGamepadUIShared_PathProperty_DashboardBarActions_BarMenuItem {
	optional int32 type = 1 [(.description) = "enum"];
	optional uint32 parent_menu_action_id = 2;
	optional uint32 action_id = 3;
}

message CVRGamepadUIShared_PathProperty_DashboardTabs {
	repeated .CVRGamepadUIShared_PathProperty_DashboardTabs_Tab tabs = 1;
	optional uint32 selected_tab_id = 2;
	optional uint32 deprecated_vr_settings_tab_id = 3;
	optional uint32 vr_steam_tab_id = 4;
}

// Used by: common.proto
message CVRGamepadUIShared_PathProperty_DashboardTabs_Tab {
	optional uint32 tab_id = 1;
	optional bool visible_in_dashboard_bar = 2;
	optional string display_name = 3;
	optional .CVRGamepadUIShared_DEPRECATED_DashboardTabIcon deprecated_icon = 4;
	optional bool visible_in_dashboard_bar_hamburger_menu = 5;
	optional .CVRGamepadUIShared_Icon icon = 6;
	optional uint32 associated_frame_id = 7;
}

message CVRGamepadUIShared_PathProperty_DesktopWindows {
	repeated .CVRGamepadUIShared_PathProperty_DesktopWindows_Window windows = 1;
}

// Used by: common.proto
message CVRGamepadUIShared_PathProperty_DesktopWindows_Window {
	optional uint32 window_id = 1;
	optional uint32 hwnd = 2;
	optional string title = 3;
	optional uint32 tab_id = 4;
}

message CVRGamepadUIShared_PathProperty_HMDSettings {
	optional float display_brightness_user_value = 1;
	optional float display_brightness_min = 2;
	optional float display_brightness_max = 3;
	optional float display_refresh_rate_value = 4;
	repeated float display_refresh_rates_available = 5;
	optional bool supersample_manual_override = 10;
	optional float supersample_scale_value = 11;
	optional float supersample_scale_min = 12;
	optional float supersample_scale_max = 13;
	optional float supersample_scale_step = 14;
	repeated uint32 supersample_effective_resolution = 15;
	optional uint32 frames_to_throttle_value = 20;
	optional bool motion_smoothing_value = 21;
	optional string performance_profile_value = 50;
	optional bool perf_graph_in_hmd_value = 51;
	optional bool record_vr_stats_value = 52;
}

message CVRGamepadUIShared_PathProperty_PowerOptions {
	optional bool can_sleep = 1;
	optional bool can_shutdown = 2;
	optional bool can_restart_system = 3;
	optional bool can_exitvr = 4;
}

message CVRGamepadUIShared_PathProperty_RunningApps {
	repeated .CVRGamepadUIShared_PathProperty_RunningApps_App apps = 1;
}

// Used by: common.proto
message CVRGamepadUIShared_PathProperty_RunningApps_App {
	optional uint32 app_id = 1;
	optional uint64 game_id = 2;
	optional string display_name = 3;
	optional int32 composition_state = 4 [(.description) = "enum"];
	optional string app_overlay_overlay_key = 5;
}

message CVRGamepadUIShared_PathProperty_VRVersionInfo {
	optional string version = 1;
	optional uint32 webpack_build_timestamp = 2;
	optional string hmd_tracking_info = 3;
}

// Used by: common.proto
message VRLink_Frame_Additional {
	optional .CVRGamepadUIShared_PathProperty_DashboardTabs_Tab tab = 1;
	optional .CVRGamepadUIShared_Icon icon = 2;
	optional bool is_currently_visible = 3;
	optional bool should_render_frame_controls = 4;
	optional bool should_suppress_panel_backsides = 5;
	optional string title = 6;
}

message VRLink_Message_Frames {
	repeated .VRLink_Message_Frames_Item frames = 1;
}

// Used by: common.proto
message VRLink_Message_Frames_Item {
	optional .CVRGamepadUI_Frame frame = 1;
	optional .VRLink_Frame_Additional frame_additional = 2;
}

message VRLink_ShowSteamVRSettings {
	optional string page = 1;
	optional string page_section = 2;
}

message VRLink_UnifiedDashboard_State {
	optional bool dashboard_visible = 2;
	optional uint32 dashboard_frame_id = 3;
}

